### PR TITLE
Updates to Readmes

### PR DESCRIPTION
**Pull request by thomaseichhorn**
Updated Readmes, changed file positions, edited CMakelists to prevent some warnings...

### CODE REVIEW

**Comment by IngoKaiser** [comment]
@thomaseichhorn @iluxa please check conflict

when ready to merge, please do so.

**Comment by iluxa** [comment]
@thomaseichhorn is it required to pull changes from master to your branch first?

**Comment by iluxa** [comment]
build with docker instructions are disappeared, Dockerfile.ubuntu removed, but Dockerfile.arch exists
Are that expected changes?

**Comment by thomaseichhorn** [comment]
Oh, they got lost on the way :)

**Pull request merged**
