### PR TITLE
Driver's CMake stuff refactoring

### PR DESCRIPTION
**Pull request by dmitigr**
Refactored CMake stuff. /driver/CMakeLists.txt now resides in /CMakeLists.txt.
We can add an option to /CMakeLists.txt to build firmware if needed (i.e. merge firmware/src/CMakeLists.txt into /CMakeLists.txt) for simplicity.

### CODE REVIEW

**Comment by dmitigr** [comment]
Okay, I've added building firmware to top-level CMakeLists.

**Comment by begodev** [comment]
I'd like to clarify is there any difference with automated-build branch?

**Comment by begodev** [comment]
I'd like to clarify the difference with automated-build branch. Is it stale?
https://github.com/panda-official/TimeSwipe/tree/automated-build

**Comment by dmitigr** [comment]
> I'd like to clarify the difference with automated-build branch. Is it stale?
> https://github.com/panda-official/TimeSwipe/tree/automated-build

Yes, this is newer than `automated-build`. This includes refactoring of CMake stuff for firmware.

**Comment by begodev** [comment]
It seems that cross-compilation of the firmware under Debian-10 is no longer working...
When building from the top-level

**Comment by dmitigr** [comment]
@begodev Could you please provide error output describing the problem?

**Comment by begodev** [comment]
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/arm-none-eabi-gcc 
Build flags: 
Id flags:  

The output was:
1
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
/tmp/building/package/build/arm-none-eabi/newlib/libc/stdlib/../../../../../newlib/libc/stdlib/exit.c:64: undefined reference to `_exit'
collect2: error: ld returned 1 exit status


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/arm-none-eabi-g++ 
Build flags: 
Id flags:  

The output was:
1
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
/tmp/building/package/build/arm-none-eabi/newlib/libc/stdlib/../../../../../newlib/libc/stdlib/exit.c:64: undefined reference to `_exit'
collect2: error: ld returned 1 exit status

**Comment by begodev** [comment]
Something is missing in compiler/linker options? Probably --specs=nosys.specs ?

**Comment by dmitigr** [comment]
> Something is missing in compiler/linker options? Probably --specs=nosys.specs ?

Well, it's specified actually in `panda.cmake`:
```
set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
```

What CMake version you use?

**Comment by dmitigr** [comment]
Could you please try the latest commit?

**Comment by begodev** [comment]
**Now the cross-compilation is working on the host PC, but neither driver building nor firmware building are  working on the target rPI:
When building the driver I get:**

Explicit Linking with atomic library
CMake Error at CMakeLists.txt:410 (target_link_libraries):
The keyword signature for target_link_libraries has already been used with
the target "timeswipe".  All uses of target_link_libraries with a target
must be either all-keyword or all-plain.

The uses of the keyword signature are here:
CMakeLists.txt:401 (target_link_libraries)

CHECK_PASSReady to build the driver.
Configuring incomplete, errors occurred

**And when building the firmware with -DPANDA_BUILD_FIRMWARE=1**

Could NOT find Boost
CMake Error at CMakeLists.txt:84 (message):
Boost not found.

But the Boost is not required by the firmware
rPI's cmake version: cmake version 3.13.4

**Comment by dmitigr** [comment]
> **Now the cross-compilation is working on the host PC, but neither driver building nor firmware building are working on the target rPI

Fixed, thanks!

**Comment by begodev** [comment]
Ok, driver building looks good, but there is still the same issue of building the firmware both on PC & rPI because of missing , --specs=nosys.specs.
What could it be? Maybe just to set some custom variable for the linker flags?

**Comment by dmitigr** [comment]
> Ok, driver building looks good, but there is still the same issue of building the firmware both on PC & rPI because of missing , --specs=nosys.specs.
> What could it be? Maybe just to set some custom variable for the linker flags?

I've just tried out to build on one of our RPi machines and it works for me. Please try to create fresh build directory and try to build again since CMAKE_EXE_LINKER_FLAGS is a cache variable.

**Comment by begodev** [comment]
> Please try to create fresh build directory and try to build again since CMAKE_EXE_LINKER_FLAGS is a cache variable.

Yes, I did that before...

But with the newest commit it seems to be working now.
I'm going to update the Readme and then merge.
Thank you!

**Comment by begodev** [comment]
I fixed some things in Readmes, Driver emulation build and Examples.
And then just followed Readme instructions.
Everything works perfectly on rPI except PWM example while linking statically with timeswipe lib:

**[100%] Linking CXX executable pwm_static
/usr/bin/ld: ../../../../build/libtimeswipe.a(timeswipe.cpp.o): in function `TimeSwipeImpl::_pollerLoop(std::function<void (SensorsData, unsigned long long)>)':
timeswipe.cpp:(.text+0x3400): undefined reference to `__atomic_fetch_and_8'
/usr/bin/ld: ../../../../build/libtimeswipe.a(timeswipe.cpp.o): in function `std::__atomic_base<unsigned long long>::operator++()':
timeswipe.cpp:(.text._ZNSt13__atomic_baseIyEppEv[_ZNSt13__atomic_baseIyEppEv]+0x28): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/pwm_static.dir/build.make:85: pwm_static] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/pwm_static.dir/all] Error 2
make: *** [Makefile:84: all] Error 2**

Also I think it should be checked on MacOS and Arch because too many changes have been made...

**Comment by begodev** [comment]
Fixed PWM example...

**Comment by begodev** [comment]
fixed driver cross compilation for Debian/Ubuntu

**Comment by begodev** [comment]
added default firmware build type

**Pull request merged**
