### PR TITLE
Issue16 optimizing board interface

### PR DESCRIPTION
**Pull request by begodev**
Please, checkout new JSON commands feature and  description of the communication protocol

### CODE REVIEW

**Review by IngoKaiser — APPROVED** [review]
I didn't test changes. Hope you did ;)

**Review by i5abell — COMMENTED** [review]
@begodev json object is not found.. I tested it with the rPIspi terminal. It is maybe not the latest version, but it has worked with the newer firmware versions.

Bildschirmfoto vom 2019-11-28 12-33-35

**Comment by begodev** [comment]
@i5abell; Have you built an actual version?
image

**Comment by begodev** [comment]
from the branch?

**Comment by begodev** [comment]
> I didn't test changes. Hope you did ;)

Sure I've tested it before uploading...

**Comment by i5abell** [comment]
> from the branch?

Yes, I built a new firmware version from the branch. But I don't need a new driver version, right?

**Comment by begodev** [comment]
> But I don't need a new driver version, right?

Yes it is not required...How have you built it? From the command line?

**Comment by i5abell** [comment]
> > But I don't need a new driver version, right?
> 
> Yes it is not required...How have you built it? From the command line?

Yes, I downloaded the branch to my local repository and built it from the command line. I tried again, but I still get these error messages..

Ok, I've seen now that some changes have not been downloaded into my local branch.. the file jsondisp.cpp for example. The new file from GitHub is not downloaded, neither by git fetch nor by git pull.. how can that be?

**Comment by begodev** [comment]
@i5abell:

I've checked it once again: just have cloned the repo, checkout to this branch, mkdir build, cd build, cmake.., make

the build settings(flags) are: -O0  -ffunction-sections -fdata-sections -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c++17.

So I assume it is working with the default settings...

Maybe you have built with some optimization, but then it should be checked separately...

**Comment by i5abell** [comment]
It was not a problem of building process but of creating the local branch correctly. Sorry, this was my fault. It is working now.

**Pull request merged**
