### PR TITLE
multithread driver read implementation; add 32bit debian support

### PR DESCRIPTION
**Pull request by iluxa**
https://github.com/panda-official/TimeSwipe/issues/15
multithread driver read implementation
add 32bit debian support

### CODE REVIEW

**Comment by IngoKaiser** [comment]
just to be sure - if I get it right 32bit built is not added to Mac built right?

**Comment by iluxa** [comment]
yes, I need to change osx doc to provide both 64 and 32 bit build

**Comment by IngoKaiser** [comment]
ok, please open new issue for that but merge that for now... no priority atm - can you estimate workload?

**Comment by iluxa** [comment]
added https://github.com/panda-official/TimeSwipe/issues/24

**Pull request merged**
