### PR TITLE
Issue6 documentation of event system

### PR DESCRIPTION
**Pull request by begodev**
A description for the EventSystem: docs/Communication/EventSystem.md

### CODE REVIEW

**Comment by IngoKaiser** [comment]
@begodev since your maintainer - would you do merges on your own or is any permission missing here? ;)

**Review by i5abell — APPROVED** [review]
Everything is fine. It can be merged.

**Comment by IngoKaiser** [comment]
ok, got review intention ;)

**Comment by begodev** [comment]
> @begodev since your maintainer - would you do merges on your own or is any permission missing here? ;)

I just was trying to follow a road map: "as soon as you are done with the task, please change the label to "in review" (so that ingo or isabel can check and be up to date)"

But more freedom is ok.

**Pull request merged**
